services:
  netbox:
    image: netbox:latest-plugins
    build:
      context: .
      dockerfile: Dockerfile-Plugins
    pull_policy: never

  netbox-worker:
    image: netbox:latest-plugins
    pull_policy: never

  netbox-housekeeping:
    image: netbox:latest-plugins
    pull_policy: never
