version: '3.8'

networks:
  mediaproxy:
    external: true

services:
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - TZ=America/Chicago
    labels:
      - traefik.docker.network=mediaproxy
      - traefik.enable=true
      - traefik.http.routers.flare.entrypoints=websecure
      - traefik.http.routers.flare.rule=Host(`flare.u-acres.com`)
      - traefik.http.routers.flare.service=flare
      - traefik.http.services.flare.loadbalancer.server.port=8191
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - mediaproxy
    restart: unless-stopped
